# Generated by Django 4.2 on 2023-04-27 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coins',
            new_name='Coin',
        ),
    ]
